const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      featured: false,
      sku: 'free-shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      featured: false,
      sku: 'fit-shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      featured: false,
      sku: 'slim-shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking pants',
      featured: false,
      sku: 'golf-pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
      featured: false,
      sku: 'fit-pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pants',
      featured: false,
      sku: 'classic-pants',
    },
    {
      name: 'Kingsons Anti Theft Smart Backpack',
      slug: 'anti-theft-smart-backpack',
      category: 'Bags',
      image: '/images/KY3148W-G.png',
      price: 999,
      brand: 'Kingsons',
      rating: 4.5,
      numReviews: 5,
      countInStock: 20,
      description: '15.6" Kingsons Anti Theft dark grey smart backpack',
      featured: false,
      sku: 'KY3148W-G',
    },
    {
      name: 'Connex SlimBook2 Laptop Celeron 3350',
      slug: 'connex-slimbook-2-rose-gold',
      category: 'Laptops',
      image: '/images/L1420-RG.png',
      price: 3899,
      brand: 'Connex',
      rating: 4.5,
      numReviews: 5,
      countInStock: 20,
      description:
        'Connex SlimBook2 laptop Celeron 3350 3/32GB 1366x768 HDD bay 7000mAh - Rose Gold',
      featured: false,
      sku: 'L1420-RG',
    },
    {
      name: 'Rocka Chaser 1080 Full HD Dash Camera',
      slug: 'rocka-chaser-1080-dash-camera',
      category: 'Cameras',
      image: '/images/RK-1008-BK.png',
      price: 899,
      brand: 'Rocka',
      rating: 4.5,
      numReviews: 5,
      countInStock: 20,
      description: 'Rocka Chaser 1080 Full HD Dash Camera',
      featured: false,
      sku: 'RK-1008-BK',
    },
    {
      name: 'Rocka Isolate NC Bluetooth Headphones',
      slug: 'rocka-isolate-bluetooth-headphones',
      category: 'Headphones',
      image: '/images/RK-2111-BK.png',
      price: 899,
      brand: 'Rocka',
      rating: 4.0,
      numReviews: 8,
      countInStock: 5,
      description:
        'Rocka Isolate series active noise cancelling bluetooth headphones',
      featured: false,
      sku: 'RK-2111-BK',
    },
    {
      name: 'SanDisk 16GB Cruzer Blade USB Flash Drive',
      slug: 'sandisk-cruzer-blade-usb-flash-drive-16GB',
      category: 'Flash Drives',
      image: '/images/SDCZ50-016G-B35.png',
      price: 89,
      brand: 'Sandisk',
      rating: 4.2,
      numReviews: 11,
      countInStock: 35,
      description:
        'SanDisk 16GB Cruzer Blade USB Flash Drive - Plug & Play USB 2.0',
      featured: false,
      sku: 'SDCZ50-016G-B35',
    },
    {
      name: 'SanDisk 64GB Cruzer Blade USB Flash Drive',
      slug: 'sandisk-cruzer-blade-usb-flash-drive-64GB',
      category: 'Flash Drives',
      image: '/images/SDCZ50-064G-B35.png',
      price: 199,
      brand: 'Sandisk',
      rating: 4.5,
      numReviews: 20,
      countInStock: 22,
      description:
        'SanDisk 64GB Cruzer Blade USB Flash Drive - Plug & Play USB 2.0',
      featured: false,
      sku: 'SDCZ50-064G-B35',
    },
    {
      name: 'Supanova Pompom Ladies Laptop Bag Taupe',
      slug: 'supanova-pompom-taupe-ladies-laptop-bag',
      category: 'Bags',
      image: '/images/sn-1000-tp.png',
      price: 399,
      brand: 'Supanova',
      rating: 4.0,
      numReviews: 8,
      countInStock: 2,
      description: 'Supanova Pompom Ladies Laptop Bag Taupe',
      featured: false,
      sku: 'sn-1000-tp',
    },
    {
      name: 'Supanova Kate Duffle Grey Mel',
      slug: 'supanova-kate-duffle-bag-grey',
      category: 'Bags',
      image: '/images/SN-1002-GR.png',
      price: 329,
      brand: 'Supanova',
      rating: 3.9,
      numReviews: 5,
      countInStock: 6,
      description: 'Supanova Kate Duffle Grey Mel',
      featured: false,
      sku: 'SN-1002-GR',
    },
    {
      name: 'Sony SRS-XB23 Extra Bass Wireless Speaker',
      slug: 'sony-srs-xb23-rce-wireless-speaker',
      category: 'Speakers',
      image: '/images/srs-xb23-rce.png',
      price: 1799,
      brand: 'Sony',
      rating: 4.2,
      numReviews: 7,
      countInStock: 8,
      description: 'Sony SRS-XB23 Extra Bass Wireless Speaker Coral',
      featured: false,
      sku: 'SRS-XB23/RCE',
    },
    {
      name: 'Sony SRS-XB33 Extra Bass Wireless Speaker',
      slug: 'sony-srs-xb33-bce-wireless-speaker',
      category: 'Speakers',
      image: '/images/SRS-XB33-BCE.png',
      price: 2699,
      brand: 'Sony',
      rating: 4.0,
      numReviews: 3,
      countInStock: 3,
      description: 'Sony SRS-XB33 Extra Bass Wireless Speaker Black',
      featured: false,
      sku: 'SRS-XB33/BCE',
    },
    {
      name: 'Travelwize Luggage Polar 60cm Navy Blue',
      slug: 'travelwize-polar-series-60cm-navy-blue',
      category: 'Bags',
      image: '/images/TW-1003-BL.png',
      price: 949,
      brand: 'Travelwize',
      rating: 4.2,
      numReviews: 5,
      countInStock: 10,
      description: 'Travelwize Luggage Polar Series 60cm Navy Blue',
      featured: false,
      sku: 'TW-1003-BL',
    },
    {
      name: 'Volkano Impulse Bluetooth Headphones',
      slug: 'volkano-impulse-bluetooth-headphones',
      category: 'Headphones',
      image: '/images/VB-VH100-BLK.png',
      price: 319,
      brand: 'Volkano',
      rating: 4.5,
      numReviews: 8,
      countInStock: 15,
      description: 'Volkano Impulse Series Bluetooth Headphones - Black',
      featured: false,
      sku: 'VB-VH100-BLK',
    },
    {
      name: 'Volkano Power Bank Erupt Series 4000 mAh',
      slug: 'volkano-erupt-power-bank',
      category: 'Power Bank',
      image: '/images/VE801-B.png',
      price: 229,
      brand: 'Volkano',
      rating: 4.0,
      numReviews: 10,
      countInStock: 10,
      description: 'Volkano Power Bank Erupt Series 4000 mAh',
      featured: false,
      sku: 'VE801-B',
    },
    {
      name: 'Volkano Titanium Earphone',
      slug: 'volkano-titanium-earphones-gun-metal',
      category: 'Earphones',
      image: '/images/VK-1003-GM.png',
      price: 99,
      brand: 'Volkano',
      rating: 4.2,
      numReviews: 20,
      countInStock: 50,
      description: 'Volkano Titanium Series AUX Earphone - Gun Metal',
      featured: false,
      sku: 'VK-1003-GM',
    },
    {
      name: 'VolkanoX Asista Bluetooth Headphones',
      slug: 'volkanox-asista-bluetooth-headphones-brown',
      category: 'Headphones',
      image: '/images/vk-1009-h01.png',
      price: 569,
      brand: 'Volkano',
      rating: 4.5,
      numReviews: 22,
      countInStock: 35,
      description: 'VolkanoX Asista Bluetooth Headphones - H01 Brown',
      featured: false,
      sku: 'vk-1009-h01',
    },
    {
      name: 'Volkano Aeon Bluetooth Earphones',
      slug: 'volkanox-aeon-bluetooth-earphones-red',
      category: 'Earphones',
      image: '/images/VK-1010-RD.png',
      price: 289,
      brand: 'Volkano',
      rating: 4.0,
      numReviews: 15,
      countInStock: 30,
      description:
        'Volkano Aeon + Series Bluetooth Earphones with Neckband - Red',
      featured: false,
      sku: 'VK-1010-RD',
    },
    {
      name: 'Volkano Marathon Bluetooth Earphones',
      slug: 'volkanox-marathon-bluetooth-earphones-black',
      category: 'Earphones',
      image: '/images/VK-1101-BK.png',
      price: 319,
      brand: 'Volkano',
      rating: 4.2,
      numReviews: 13,
      countInStock: 30,
      description:
        'Volkano Marathon series Bluetooth earphone with neckband - Black',
      featured: false,
      sku: 'VK-1101-BK',
    },
    {
      name: 'VolkanoX Asista Bluetooth Earphones N01',
      slug: 'volkanox-asista-bluetooth-earphones-black-n01',
      category: 'Earphones',
      image: '/images/VK-1102-N01-BK.png',
      price: 289,
      brand: 'Volkano',
      rating: 4.5,
      numReviews: 60,
      countInStock: 30,
      description: 'VolkanoX Asista Bluetooth Earphones N01 - Black',
      featured: false,
      sku: 'VK-1102-N01-BK',
    },
    {
      name: 'VolkanoX Asista Bluetooth Earphones E01',
      slug: 'volkanox-asista-bluetooth-earphones-black-e01',
      category: 'Earphones',
      image: '/images/VK-1103-E01-BK.png',
      price: 289,
      brand: 'Volkano',
      rating: 4.5,
      numReviews: 60,
      countInStock: 30,
      description: 'VolkanoX Asista Bluetooth Earphones E01 - Black',
      featured: false,
      sku: 'VK-1103-E01-BK',
    },
  ],
};
export default data;
